Add-Type -AssemblyName System.Drawing
$img = [System.Drawing.Image]::FromFile("i:\nhmpprojects\dxb_reporting_app\assets\logo.png")
$bmp = New-Object System.Drawing.Bitmap($img.Width, $img.Height)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.Clear([System.Drawing.Color]::White)
$g.DrawImage($img, 0, 0, $img.Width, $img.Height)
$bmp.Save("i:\nhmpprojects\dxb_reporting_app\assets\logo.jpg", [System.Drawing.Imaging.ImageFormat]::Jpeg)
$g.Dispose()
$bmp.Dispose()
$img.Dispose()
